---
- hosts: master
  become: true
  tasks:
    - name: Updates
      apt:
        update_cache: true
    # kubectl not being found
    - name: Install Kubectl
      apt:
        name: kubectl
        state: present
        force: yes
    - name: Create an Empty file for Kubeadm configuring
      copy:
        content: ""
        dest: /etc/kubernetes/kubeadm-config.yaml
        force: false

    - name: Configure container runtime
      blockinfile:
        path: /etc/kubernetes/kubeadm-config.yaml
        block: |
          kind: ClusterConfiguration
          apiVersion: kubeadm.k8s.io/v1beta3
          networking:
            podSubnet: "10.244.0.0/16"
          ---
          kind: KubeletConfiguration
          apiVersion: kubelet.config.k8s.io/v1beta1
          runtimeRequestTimeout: "15m"
          cgroupDriver: "systemd"
          systemReserved:
            cpu: 100m
            memory: 350M
          kubeReserved:
            cpu: 100m
            memory: 50M
          enforceNodeAllocatable:
          - pods

    - name: Initialize the cluster
      shell: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml >> cluster_initialized.log
      args:
        chdir: /home/vagrant # depends on env, validate this
        creates: cluster_initialized.log

    - name: Create .kube directory
      become: true
      become_user: vagrant # depends on env, validate this
      file:
        path: $HOME/.kube
        state: directory
        mode: "0755"

    - name: Copy admin.conf to User's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config # depends on env, validate this
        remote_src: true
        owner: vagrant # depends on env, validate this

    - name: Install Pod Network
      become: true
      become_user: vagrant # depends on env, validate this
      shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.log
      args:
        chdir: $HOME
        creates: pod_network_setup.log
...
