---
master:
    hosts:
        web:
            ansible_host: 54.159.67.44
            ansible_port: 2222
            ansible_user: vagrant
            ansible_private_key_file: .vagrant/machines/master/vmware_desktop/private_key
worker1:
    hosts:
        web:
            ansible_host: 3.85.194.142
            ansible_port: 2222
            ansible_user: vagrant
            ansible_private_key_file: .vagrant/machines/worker1/vmware_desktop/private_key
worker2:
    hosts:
        web:
            ansible_host: 54.167.202.163
            ansible_port: 2222
            ansible_user: vagrant
            ansible_private_key_file: .vagrant/machines/worker2/vmware_desktop/private_key
...