---
mast:
    hosts:
        master:
            ansible_host: 127.0.0.1
            ansible_port: 2222
            ansible_user: vagrant
            ansible_private_key_file: .vagrant/machines/master/vmware_desktop/private_key
work:
    hosts:
        worker1:
            ansible_host: 127.0.0.1
            ansible_port: 2200
            ansible_user: vagrant
            ansible_private_key_file: .vagrant/machines/worker1/vmware_desktop/private_key
        worker2:
            ansible_host: 127.0.0.1
            ansible_port: 2201
            ansible_user: vagrant
            ansible_private_key_file: .vagrant/machines/worker2/vmware_desktop/private_key
...